export const IPC = {
  DETECT_DIRECTORY: 'detect:directory',
  PROCESS_START: 'process:start',
  PROCESS_STOP: 'process:stop',
  PROCESS_INPUT: 'process:input',
  PROCESS_OUTPUT: 'process:output',
  PROCESS_STATUS: 'process:status',
  PROCESS_EXIT: 'process:exit',
  PROCESS_RESIZE: 'process:resize',
  AI_COMMIT_RUN: 'ai-commit:run',
  AI_COMMIT_OUTPUT: 'ai-commit:output',
  AI_COMMIT_STATUS: 'ai-commit:status',
  GIT_GET_LATEST_COMMIT: 'git:getLatestCommit',
  CONFIG_GET: 'config:get',
  CONFIG_GET_THEME_SYNC: 'config:get-theme-sync',
  CONFIG_SET: 'config:set',
  DIALOG_SELECT_DIRECTORY: 'dialog:selectDirectory',
  SHELL_OPEN_EXTERNAL: 'shell:openExternal',
  WSL_GET_CAPABILITY: 'wsl:getCapability',
  TMUX_LIST_SESSIONS: 'tmux:list-sessions',
  TMUX_KILL_SESSION: 'tmux:kill-session',
  RUNTIME_START: 'runtime:start',
  RUNTIME_DIAGNOSTICS: 'runtime:diagnostics',
  RUNTIME_LIST_ENTRIES: 'runtime:list-entries',
  SHELL_OPEN_TERMINAL: 'shell:open-terminal',
  SHELL_OPEN_FOLDER: 'shell:openFolder',
  SHELL_OPEN_VSCODE: 'shell:openVsCode',
} as const
