const LEGACY_BROWSER_DATA_CLEANUP_RELATIVE_PATHS = [
  'session',
  'Cache',
  'Code Cache',
  'GPUCache',
  'DawnGraphiteCache',
  'DawnWebGPUCache',
  'ShaderCache',
  'GrShaderCache',
  'blob_storage',
  'Local Storage',
  'Session Storage',
  'Preferences',
  'Network',
  'DIPS',
  'DIPS-wal',
  'SharedStorage',
  'SharedStorage-wal',
  'Shared Dictionary',
  'Dictionaries',
  'Cookies',
  'Cookies-journal',
  'IndexedDB',
  'databases',
  'File System',
  'Service Worker',
  'WebStorage',
]

export { LEGACY_BROWSER_DATA_CLEANUP_RELATIVE_PATHS }
